# This file was generated by GoReleaser. DO NOT EDIT.
cask "blit" do
  version "0.2.12"

  on_macos do
    on_intel do
      url "https://github.com/blitui/blit/releases/download/v#{version}/blit_#{version}_darwin_amd64.tar.gz"
      sha256 "3fcbc107962c06c947d71d16ea94e38911ed329a29613277c85aa507a6fd4f30"
    end
    on_arm do
      url "https://github.com/blitui/blit/releases/download/v#{version}/blit_#{version}_darwin_arm64.tar.gz"
      sha256 "554ef93423aec88b98639d01b83d0cbb08f50506511b9c6cf175954ca46fc6e1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/blitui/blit/releases/download/v#{version}/blit_#{version}_linux_amd64.tar.gz"
      sha256 "b0d76cac56c2dec51d277b0ac1dbf7623a568188482da137212a0dea19018c25"
    end
    on_arm do
      url "https://github.com/blitui/blit/releases/download/v#{version}/blit_#{version}_linux_arm64.tar.gz"
      sha256 "580d5b35fdcd76808605828f6923eb880a24b9ba1d0a10c8ccd5b5d3f8a54d44"
    end
  end

  name "blit"
  desc "CLI for blit — the pragmatic Go TUI toolkit"
  homepage "https://github.com/blitui/blit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blit"

  # No zap stanza required

end
