# This file was generated by GoReleaser. DO NOT EDIT.
cask "blit" do
  version "0.2.19"

  on_macos do
    on_intel do
      url "https://github.com/blitui/blit/releases/download/v#{version}/blit_#{version}_darwin_amd64.tar.gz"
      sha256 "0050c78b426cb5b1cb2b778510816ff57ccb3a35512d1c45dbeef937d8f92ed7"
    end
    on_arm do
      url "https://github.com/blitui/blit/releases/download/v#{version}/blit_#{version}_darwin_arm64.tar.gz"
      sha256 "0902e8f4c90d32ee65424211c227a51bb5050fd09ab9feaf8e67b585e7f1e6ba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/blitui/blit/releases/download/v#{version}/blit_#{version}_linux_amd64.tar.gz"
      sha256 "f9f0b48a0af901196bc97029033ec465186601207c5ce7f4f2a0cff0a3eb659a"
    end
    on_arm do
      url "https://github.com/blitui/blit/releases/download/v#{version}/blit_#{version}_linux_arm64.tar.gz"
      sha256 "64ea2edc00394b6ab8540b241eed9885592c0904b3a618f5a8ee48c7ce687fbe"
    end
  end

  name "blit"
  desc "CLI for blit — the pragmatic Go TUI toolkit"
  homepage "https://github.com/blitui/blit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blit"

  # No zap stanza required

end
