# This file was generated by GoReleaser. DO NOT EDIT.
cask "blit" do
  version "0.2.21"

  on_macos do
    on_intel do
      url "https://github.com/blitui/blit/releases/download/v#{version}/blit_#{version}_darwin_amd64.tar.gz"
      sha256 "4a04f182b0b5aa2e5b3c4edd0db592383cd6f22bfa10a6186ca302015eef8fd1"
    end
    on_arm do
      url "https://github.com/blitui/blit/releases/download/v#{version}/blit_#{version}_darwin_arm64.tar.gz"
      sha256 "e0772231cfe2579b414f2f0b900534928674990aa6607595790d42cf317e12e1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/blitui/blit/releases/download/v#{version}/blit_#{version}_linux_amd64.tar.gz"
      sha256 "32d79d4ae529e404ce04ee907a9211cbc19987762e57b97bcbc4d5166b41dfea"
    end
    on_arm do
      url "https://github.com/blitui/blit/releases/download/v#{version}/blit_#{version}_linux_arm64.tar.gz"
      sha256 "34a70fd47f8d2f822cb66e48e07ba041aa96a66a0ade5751a0d5bc4e2774708e"
    end
  end

  name "blit"
  desc "CLI for blit — the pragmatic Go TUI toolkit"
  homepage "https://github.com/blitui/blit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blit"

  # No zap stanza required

end
